import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import type { Metadata } from "next";

import AuthProvider from "../components/AuthProvider";

import "src/styles/globals.css";
import QueryProvider from "@/components/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// do not cache this layout
export const revalidate = 0;

export default async function RootLayout({ children }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body>
        <div>
          <main>
            <QueryProvider>
              <AuthProvider accessToken={accessToken}>{children}</AuthProvider>
            </QueryProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
