import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import type { Metadata } from "next";

import AuthProvider from "../components/AuthProvider";

import "src/styles/globals.css";
import QueryProvider from "@/components/QueryProvider";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

export const metadata: Metadata = {
  title: "Microblogging",
  description: "Generated by create next app",
};

export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;

  return (
    <html lang="en">
      <body>
        <div>
          <main>
            <QueryProvider>
              <Header session={session} />
              <AuthProvider accessToken={accessToken}>{children}</AuthProvider>
              <Footer />
            </QueryProvider>
          </main>
        </div>
      </body>
    </html>
  );
}
